codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: 80...100

  status:
    project:
      default:
        target: 95%
        threshold: 1%
        if_ci_failed: error

    patch:
      default:
        target: 90%
        threshold: 2%

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

ignore:
  - "**/*.config.ts"
  - "**/*.config.js"
  - "**/types/**"
  - "**/*.d.ts"
  - "**/*.test.ts"
  - "**/*.spec.ts"
  - "src/test-setup.ts"
  - "dist/**"
  - "node_modules/**"
