import { describe, expect, it } from 'vitest';

import { firstMatch } from './check-attribution.mjs';

describe('check-attribution firstMatch', () => {
  it.each([
    ['a Claude-Session footer', 'Claude-Session: https://claude.ai/code/session_abc'],
    ['a bare claude.ai URL', 'See https://claude.ai/code/session_x'],
    ['a Co-Authored-By bot', 'Co-Authored-By: Claude <noreply@anthropic.com>'],
    ['a robot-emoji generated line', '🤖 Generated with Claude Code'],
    ['generated by ChatGPT', 'Generated by ChatGPT'],
    ['an anthropic.com reference', 'ref anthropic.com/x'],
  ])('flags %s', (_label, text) => {
    expect(firstMatch(text)).not.toBeNull();
  });

  it.each([
    ['plain prose', 'Fix the newsletter confirm flow and add tests'],
    ['a CLAUDE.md file reference', 'Update CLAUDE.md with the new convention'],
    ['"generated with mkcert"', 'cert generated with mkcert for local dev'],
    ['a human co-author', 'Co-authored-by: Jane Roe <jane@example.com>'],
    ['the word "generated" alone', 'The sitemap is generated at build time'],
  ])('does not flag %s', (_label, text) => {
    expect(firstMatch(text)).toBeNull();
  });

  it('returns the offending line, trimmed, scanning line-by-line', () => {
    expect(firstMatch('a clean line\n  Claude-Session: https://claude.ai/x  ')).toBe('Claude-Session: https://claude.ai/x');
  });
});
