// Generated by scripts/encode-audio.mjs — do not edit by hand.
import type { AudioTrack } from '@/types/audio';

export const audioManifest: Record<string, AudioTrack[]> = {
  '1714': [
    { key: 'BRQN001/01-8-58.m4a', title: '8:58', duration: 538 },
    { key: 'BRQN001/02-2-58.m4a', title: '2:58', duration: 178 },
    { key: 'BRQN001/03-5-18.m4a', title: '5:18', duration: 318 },
  ],
  '2504': [
    { key: 'BRQN006/01-2504.m4a', title: '2504', duration: 1504 },
  ],
  'overlapse': [
    { key: 'BRQN002/01-attack-prelude.m4a', title: 'Attack (Prelude)', duration: 420 },
    { key: 'BRQN002/02-sustain-i.m4a', title: 'Sustain I', duration: 457 },
    { key: 'BRQN002/03-sustain-ii.m4a', title: 'Sustain II', duration: 363 },
    { key: 'BRQN002/04-decay-i.m4a', title: 'Decay I', duration: 323 },
    { key: 'BRQN002/05-decay-ii.m4a', title: 'Decay II', duration: 441 },
    { key: 'BRQN002/06-decay-iii.m4a', title: 'Decay III', duration: 541 },
    { key: 'BRQN002/07-release-conclusion.m4a', title: 'Release (Conclusion)', duration: 335 },
  ],
  'caligari-album': [
    { key: 'BRQN005/01-spirits-surround-us-on-every-side.m4a', title: 'Spirits Surround Us On Every Side', duration: 286 },
    { key: 'BRQN005/02-awaken-for-a-moment-from-your-dark-night.m4a', title: 'Awaken For A Moment From Your Dark Night', duration: 337 },
    { key: 'BRQN005/03-how-long-will-i-live.m4a', title: 'How Long Will I Live?', duration: 252 },
    { key: 'BRQN005/04-it-couldn-t-have-been-cesare.m4a', title: "It Couldn't Have Been Cesare...", duration: 240 },
    { key: 'BRQN005/05-we-who-are-of-noble-blood-may-not-follow-the-wishes-of-our-hearts.m4a', title: 'We Who Are Of Noble Blood May Not Follow The Wishes Of Our Hearts', duration: 191 },
  ],
  'en-veille': [
    { key: 'BRQN008/01-en-veille.m4a', title: 'En Veille', duration: 2011 },
  ],
  'contraplacado': [
    { key: 'BRQN009/01-contraplacado-se-deus-nos-der-vida-e-saude.m4a', title: 'Contraplacado (Se Deus nos der vida e saúde)', duration: 900 },
  ],
};
